version: "3.3"
services:
  app:
    container_name: app
    depends_on:
      - db
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped

  db:
    container_name: db
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
